# config.yaml
data:
  csv_path: "data/airlines_delay_sample.csv"
  db_path: "data/airlines_delay_sample.db"
  table_name: "AirlinesDelay"

model:
  name: "gpt-3.5-turbo"
  temperature: 0

evaluation:
  report_path: "report.html"
  testset_path: "testset.json"
  results_path: "evaluation_results.csv"
  num_questions: 60
  agent_description: "A chatbot answering questions about flights"
  model:
    name: "gpt-3.5-turbo"
    temperature: 0
