import logging
import os

import yaml
from dotenv import load_dotenv
from fastapi import FastAPI, Header, HTTPException
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from models import create_chat_model
from rag_fly import RagSystem
from fastapi.middleware.cors import CORSMiddleware


# Load environment variables from .env file
load_dotenv()

# Load model configuration from config.yaml
with open("config.yaml", "r") as _f:
    _config = yaml.safe_load(_f)
_model_config = _config["model"]

# Configure logging
logger = logging.getLogger(__name__)

# DEV_MODE: when True, allows falling back to the .env API key if none is provided in the request.
DEV_MODE = os.environ.get("DEV_MODE", "false").lower() in ("true", "1", "yes")

app = FastAPI(
    title="Airline RAG MVP API",
    description="FastAPI wrapper for the Airline Retrieval Augmented Generation (RAG) system.",
    version="1.0.0",
    contact={
        "name": "Michael Stähli",
        "email": "michael.w.staehli@gmail.com"
    },
    license_info={
        "name": "MIT"
    }
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Pydantic schemas for request validation
class QueryRequest(BaseModel):
    question: str = Field(..., description="The user's query or question about the airline dataset.")
    session_id: str = Field("default_session", description="The conversation session ID to persist chat history.")
    api_key: str | None = Field(None, description="Optional BYOK OpenAI API key (alternative to header).")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the RAG system.")


def _resolve_api_key(request_key: str | None) -> str:
    """
    Resolve the API key to use for a request.

    In DEV_MODE, falls back to the environment variable if no key is provided.
    In production, the request must always supply a key.
    """
    if DEV_MODE:
        api_key = request_key or os.environ.get("OPENAI_API_KEY")
    else:
        api_key = request_key

    if not api_key:
        raise HTTPException(
            status_code=401,
            detail="API key is required. Provide it via 'api_key' in the request body or 'X-OpenAI-Key' header.",
        )
    return api_key


def _build_rag_engine(api_key: str) -> RagSystem:
    """
    Build a RagSystem with the given API key.

    The key is passed directly to the LLM client and is never written to
    environment variables or the .env file.
    """
    llm = create_chat_model(
        provider=_model_config["provider"],
        model_name=_model_config["name"],
        temperature=_model_config["temperature"],
        api_key=api_key,
    )
    return RagSystem(llm=llm)


@app.post("/query", response_model=QueryResponse, tags=["RAG"])
def query_rag(payload: QueryRequest, x_openai_key: str | None = Header(None)):
    """
    Submit a question to the RAG system.

    The API key provided in the request is used to create the LLM client
    on-the-fly and is discarded after the request completes.
    Supports persistent conversational history via `session_id`.
    """
    api_key = _resolve_api_key(x_openai_key or payload.api_key)

    try:
        rag_engine = _build_rag_engine(api_key)
        answer = rag_engine.answer_question(payload.question, session_id=payload.session_id)
        return QueryResponse(answer=answer)
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Query failed.")
        raise HTTPException(status_code=500, detail="Internal server error")


@app.get("/health", tags=["Monitoring"])
def get_health():
    """
    Check the health of the API and required services.
    """
    openai_ok = DEV_MODE and bool(os.getenv("OPENAI_API_KEY"))

    return {
        "status": "healthy",
        "dev_mode": DEV_MODE,
        "openai_env_key_present": openai_ok,
    }

# Serve frontend static files (must be last so API routes take priority)
app.mount("/", StaticFiles(directory="frontend", html=True), name="frontend")