import logging
import os

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

from rag_fly import RagSystem
from fastapi.middleware.cors import CORSMiddleware


# Load environment variables from .env file
load_dotenv()

# Configure logging
logger = logging.getLogger(__name__)

app = FastAPI(
    title="Airline RAG MVP API",
    description="FastAPI wrapper for the Airline Retrieval Augmented Generation (RAG) system.",
    version="1.0.0",
    contact={
        "name": "Michael Stähli",
        "email": "michael.w.staehli@gmail.com"
    },
    license_info={
        "name": "MIT"
    }
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize ONCE when the API starts.
# It points to the database specified in config.yaml.
rag_engine = RagSystem()

# Pydantic schemas for request validation
class QueryRequest(BaseModel):
    question: str = Field(..., description="The user's query or question about the airline dataset.")
    session_id: str = Field("default_session", description="The conversation session ID to persist chat history.")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the RAG system.")


@app.post("/query", response_model=QueryResponse, tags=["RAG"])
def query_rag(payload: QueryRequest):
    """
    Submit a question to the RAG system.
    Supports persistent conversational history via `session_id`.
    """
    try:
        answer = rag_engine.answer_question(payload.question, session_id=payload.session_id)
        return QueryResponse(answer=answer)
    except Exception as e:
        raise HTTPException(status_code=500, detail="Internal server error")

@app.get("/health", tags=["Monitoring"])
def get_health():
    """
    Check the health of the API and required services.
    """

    db_ok = False

    try:
        if rag_engine.db is not None:
            rag_engine.db.run("SELECT 1;")
            db_ok = True
    except Exception as e:
        logger.exception("Database health check failed.")

    openai_ok = bool(os.getenv("OPENAI_API_KEY"))

    status = "healthy" if db_ok and openai_ok else "unhealthy"

    return {
        "status": status,
        "database_connected": db_ok,
        "openai_key_present": openai_ok,
    }