import logging
import os
import threading
import time
import uuid

import yaml
from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from models import create_chat_model
from rag_fly import RagSystem
from fastapi.middleware.cors import CORSMiddleware


# Load environment variables from .env file
load_dotenv()

# Load model configuration from config.yaml
with open("config.yaml", "r") as _f:
    _config = yaml.safe_load(_f)
_model_config = _config["model"]

# Configure logging
logger = logging.getLogger(__name__)

# DEV_MODE: when True, allows falling back to the .env API key if none is provided in the request.
DEV_MODE = os.environ.get("DEV_MODE", "false").lower() in ("true", "1", "yes")

# Session expiration timeout in seconds (30 minutes of inactivity)
SESSION_TIMEOUT_SECONDS = 30 * 60

app = FastAPI(
    title="Airline RAG MVP API",
    description="FastAPI wrapper for the Airline Retrieval Augmented Generation (RAG) system.",
    version="1.0.0",
    contact={
        "name": "Michael Stähli",
        "email": "michael.w.staehli@gmail.com"
    },
    license_info={
        "name": "MIT"
    }
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# In-memory session store
# ---------------------------------------------------------------------------
# Each session holds: api_key, rag_engine (RagSystem instance), last_active timestamp
_sessions: dict[str, dict] = {}
_sessions_lock = threading.Lock()


def _cleanup_expired_sessions():
    """Remove sessions that have been inactive longer than SESSION_TIMEOUT_SECONDS."""
    now = time.time()
    with _sessions_lock:
        expired = [
            sid for sid, data in _sessions.items()
            if now - data["last_active"] > SESSION_TIMEOUT_SECONDS
        ]
        for sid in expired:
            del _sessions[sid]
            logger.info("Session %s expired and was removed.", sid)


def _start_cleanup_thread():
    """Background daemon thread that periodically purges expired sessions."""
    def _loop():
        while True:
            time.sleep(60)
            _cleanup_expired_sessions()

    t = threading.Thread(target=_loop, daemon=True)
    t.start()


_start_cleanup_thread()


# ---------------------------------------------------------------------------
# Pydantic schemas
# ---------------------------------------------------------------------------
class CreateSessionResponse(BaseModel):
    session_id: str = Field(..., description="Unique session identifier.")

class ConfigureSessionRequest(BaseModel):
    session_id: str = Field(..., description="The session to configure.")
    api_key: str = Field(..., description="OpenAI API key for this session.")

class ConfigureSessionResponse(BaseModel):
    status: str = Field(..., description="Configuration status message.")

class DeleteSessionRequest(BaseModel):
    session_id: str = Field(..., description="The session to delete.")

class QueryRequest(BaseModel):
    question: str = Field(..., description="The user's query or question about the airline dataset.")
    session_id: str = Field(..., description="The conversation session ID.")

class QueryResponse(BaseModel):
    answer: str = Field(..., description="The answer generated by the RAG system.")


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
def _build_rag_engine(api_key: str) -> RagSystem:
    """
    Build a RagSystem with the given API key.

    The key is passed directly to the LLM client and is never written to
    environment variables or the .env file.
    """
    llm = create_chat_model(
        provider=_model_config["provider"],
        model_name=_model_config["name"],
        temperature=_model_config["temperature"],
        api_key=api_key,
    )
    return RagSystem(llm=llm)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------
@app.post("/session/create", response_model=CreateSessionResponse, tags=["Session"])
def create_session():
    """Create a new temporary session and return a unique session_id."""
    session_id = str(uuid.uuid4())
    with _sessions_lock:
        _sessions[session_id] = {
            "api_key": None,
            "rag_engine": None,
            "last_active": time.time(),
        }
    logger.info("Session %s created.", session_id)
    return CreateSessionResponse(session_id=session_id)


@app.post("/session/configure", response_model=ConfigureSessionResponse, tags=["Session"])
def configure_session(payload: ConfigureSessionRequest):
    """
    Configure a session with the user's OpenAI API key.

    The key is stored only in temporary in-memory session state and is never
    written to .env or persisted permanently.
    """
    with _sessions_lock:
        session = _sessions.get(payload.session_id)
        if session is None:
            raise HTTPException(status_code=404, detail="Session not found.")
        session["api_key"] = payload.api_key
        session["rag_engine"] = _build_rag_engine(payload.api_key)
        session["last_active"] = time.time()
    logger.info("Session %s configured.", payload.session_id)
    return ConfigureSessionResponse(status="configured")


@app.post("/session/delete", tags=["Session"])
def delete_session(payload: DeleteSessionRequest):
    """Delete a session and all associated data (API key, chat history)."""
    with _sessions_lock:
        removed = _sessions.pop(payload.session_id, None)
    if removed is None:
        raise HTTPException(status_code=404, detail="Session not found.")
    logger.info("Session %s deleted.", payload.session_id)
    return {"status": "deleted"}


@app.post("/query", response_model=QueryResponse, tags=["RAG"])
def query_rag(payload: QueryRequest):
    """
    Submit a question to the RAG system.

    Uses the RagSystem instance stored in the session so that chat history
    is preserved across requests within the same session.
    """
    with _sessions_lock:
        session = _sessions.get(payload.session_id)
        if session is None:
            raise HTTPException(status_code=404, detail="Session not found. Please create a session first.")
        if session["rag_engine"] is None:
            raise HTTPException(status_code=400, detail="Session not configured. Please submit your API key first.")
        session["last_active"] = time.time()
        rag_engine = session["rag_engine"]

    try:
        answer = rag_engine.answer_question(payload.question, session_id=payload.session_id)
        return QueryResponse(answer=answer)
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("Query failed.")
        raise HTTPException(status_code=500, detail="Internal server error")


@app.get("/health", tags=["Monitoring"])
def get_health():
    """Check the health of the API and required services."""
    openai_ok = DEV_MODE and bool(os.getenv("OPENAI_API_KEY"))
    return {
        "status": "healthy",
        "dev_mode": DEV_MODE,
        "openai_env_key_present": openai_ok,
    }

# Serve frontend static files (must be last so API routes take priority)
app.mount("/", StaticFiles(directory="frontend", html=True), name="frontend")
